# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nflan.proto\x12\x04\x66lan\"\x17\n\x06GetReq\x12\r\n\x05index\x18\x01 \x01(\x03\"0\n\x07GetResp\x12\x11\n\tinput_ids\x18\x01 \x03(\x03\x12\x12\n\ntarget_ids\x18\x02 \x03(\x03\"\r\n\x0bMetadataReq\"\x1d\n\x0cMetadataResp\x12\r\n\x05total\x18\x01 \x01(\x03\x32r\n\x15\x46lanProcessingDataset\x12$\n\x03Get\x12\x0c.flan.GetReq\x1a\r.flan.GetResp\"\x00\x12\x33\n\x08Metadata\x12\x11.flan.MetadataReq\x1a\x12.flan.MetadataResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flan_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETREQ']._serialized_start=20
  _globals['_GETREQ']._serialized_end=43
  _globals['_GETRESP']._serialized_start=45
  _globals['_GETRESP']._serialized_end=93
  _globals['_METADATAREQ']._serialized_start=95
  _globals['_METADATAREQ']._serialized_end=108
  _globals['_METADATARESP']._serialized_start=110
  _globals['_METADATARESP']._serialized_end=139
  _globals['_FLANPROCESSINGDATASET']._serialized_start=141
  _globals['_FLANPROCESSINGDATASET']._serialized_end=255
# @@protoc_insertion_point(module_scope)
