TEMPLATES = {
    'nsmc': [
        ("리뷰:\n{sentence}\n이 영화 리뷰 문장이 부정적입니까, 긍정적입니까? \n{options_}", "{answer}"),
        ("짧은 영화 리뷰: {sentence}\n평론가가 이 영화에 대해 긍정적으로 생각했나요, 부정적으로 생각했나요?\n{options_}", "{answer}"),
        ("영화 리뷰의 문장: {sentence}\n위의 리뷰에 근거하여 영화를 긍정적으로 보았나요, 부정적으로 보았나요?\n\n{options_}", "{answer}"),
        ("\"{sentence}\"\n이 문장의 감정은 어떻게 인식되나요? \n\n{options_}", "{answer}"),
        ("다음 문장의 감정은 긍정적입니까, 부정입니까?\n{sentence}\n{options_}", "{answer}"),
        ("다음 영화 리뷰 문장의 감정은 무엇입니까?\n{sentence}\n{options_}", "{answer}"),
        ("다음 문구는 긍정적일까요, 부정적일까요?\n\n{sentence}\n{options_}", "{answer}"),
        ("다음 리뷰는 영화에 대한 긍정적 또는 부정적 의견을 가지고 있습니까?\n\n{sentence}\n{options_}", "{answer}"),
        ("{answer}적인 영화 리뷰 작성.", "{sentence}"),
        ("{answer}적인 감정이 포함된 짧은 영화 리뷰 생성.", "{sentence}"),
    ],
    'question_pair': [
        ("{question1}\n{question2}\n이 질문들이 같다고 말씀하시겠습니까? \n{options_}", "{answer}"),
        ("{question1}\n{question2}\n이 질문들은 같은 의미라고 생각하십니까?\n{options_}", "{answer}"),
        ("{question1}\n{question2}\n\n이 두 질문은 같은 정보를 묻는 질문입니까? \n{options_}", "{answer}"),
        ("{question1}\n\n{question2}\n\n이 두 질문이 같은 질문인지 알려주세요.\n{options_}", "{answer}"),
        ("{question1}\n\n{question2}\n\n이 두 질문은 서로 의미가 같은 질문인가요?\n{options_}", "{answer}"),
        ("첫 번째 질문: {question1}\n두 번째 질문: {question2}\n이 두 질문은 같은 것을 묻고 있나요?\n{options_}", "{answer}"),
        ("질문 1: {question1}\n질문 2: {question2}\n질문 1과 2가 같은 것을 묻고 있나요?\n{options_}", "{answer}"),
        ("질문 1: {question1}\n질문 2: {question2}\n\n이 두 질문에 대한 답은 같습니까?\n{options_}", "{answer}"),
        ("다음 두 질문이 같습니까?\n{question1}\n{question2}\n\n{options_}", "{answer}"),
        ("다음 두 질문은 같은 의미인가요?\n{question1}\n{question2}\n\n{options_}", "{answer}"),
    ],
    'korquad_v1': [
        ("{title}에 대한 다음 문서에 대한 질문에 답하세요:\n\n{context}\n\n{question}", "{answer}"),
        ("이 글을 읽고 질문에 답하세요\n\n{context}\n\n{question}", "{answer}"),
        ("{context}\n{question}", "{answer}"),
        ("이 문서에 대한 질문에 답변하세요:\n{context}\n{question}", "{answer}"),
        ("이 문서에 대한 질문이 있습니다: {context}\n이 질문에 대한 답은 무엇인가요: {question}", "{answer}"),
        ("문서: {context}\n\n질문: {question}", "{answer}"),
        ("문서: {context}\n\n이 질문에 답하세요: {question}", "{answer}"),
        ("{title}\n{context}\n\nQ: {question}\nA:", "{answer}"),
        ("{title}에 대해 질문하세요.", "{question}"),
        ("이 문서의 제목은 무엇인가요:\n\n{context}", "{title}"),
    ],
    "klue_mrc": [
        ("{title}:\n\n{context}\n\n이 문서에 대한 질문에 답변해 주세요. 답변할 수 없는 질문이면 \"답변할 수 없음\"이라고 말합니다. {question}", "{answer}"),
        ("이 글을 읽고 질문에 답하세요. 답변할 수 없는 질문인 경우에는 \"답변할 수 없음\"이라고 말합니다.\n\n{context}\n\n{question}", "{answer}"),
        ("이 문서에 대한 질문이 무엇인가요? 답변할 수 없는 질문인 경우 \"답변할 수 없음\"이라고 표시합니다.\n\n{context}\n\n{question}", "{answer}"),
        ("{context}\n{question}(답변할 수 없는 질문인 경우 \"답변할 수 없음\")", "{answer}"),
        ("{context}\n이 질문에 가능한 경우 답변을 시도하세요(그렇지 않으면 \"답변할 수 없음\"이라고 답하세요): {question}", "{answer}"),
        ("{context}\n이 질문에 답변할 수 있으면 답변해 주세요(그렇지 않으면 \"답변할 수 없음\" 응답): {question}", "{answer}"),
        ("{context}\n\n가능하면 이 질문에 답변하세요(불가능하면 \"답변할 수 없음\"으로 응답): {question}", "{answer}"),
        ("이 내용을 읽으십시오: {context}\n\n{question}\n답은 무엇입니까? (답변할 수 없는 경우 \"답변할 수 없음\" 반환)", "{answer}"),
        ("이걸 읽어보세요: {context}\n이 질문에 대한 답이 있으면 이제 대답하세요(대답할 수 없으면 \"답변할 수 없음\" 반환): {question}", "{answer}"),
        ("{context}\n이 질문에 대한 답변이 있습니까(답변할 수 없으면 \"답변할 수 없음\"이라고 표시): {question}", "{answer}"),
    ],
    'kor_nli': [
        ("\"{sentence1}\"이면 \"{sentence2}\"라는 결론을 내릴 수 있습니까?\n{options_}", "{answer}"),
        ("\"{sentence1}\"이면 \"{sentence2}\"을 따라야 하나요?\n{options_}", "{answer}"),
        ("\"{sentence1}\"이면 \"{sentence2}\"가 맞나요? \n\n{options_}", "{answer}"),
        ("\"{sentence1}\"\n\n이제 \"{sentence2}\"라고 말할 수 있습니까?\n\n{options_}", "{answer}"),
        ("\"{sentence1}\"은 참 문장입니다.\n\n이것은 \"{sentence2}\"을 의미합니까?\n\n{options_}", "{answer}"),
        ("\"{sentence2}\"는 \"{sentence1}에 근거하여 정확한 진술로 보이나요?\n\n{options_}", "{answer}"),
        ("만약 문장 \"{sentence1}\"이 참이면 \"{sentence2}\"라고 결론을 내릴 수 있나요?\n\n{options_}", "{answer}"),
        ("\"{sentence1}\"이 참이면 \"{sentence2}\"라는 결론을 도출할 수 있습니까?\n\n{options_}", "{answer}"),
        ("만약 \"{sentence1}\"이면 {sentence2}\"는 참인가요?\n\n{options_}", "{answer}"),
        ("문장 1: \"{sentence1}\"\n\n문장 2: \"{sentence2}\"\n\n문장 1에 따라 문장 2는 참인가?\n\n{options_}", "{answer}"),
    ],
    'kor_sts': [  # YuJung
        ("{sentence1}\n{sentence2}\n\n이 두 문장의 텍스트 유사성을 0에서 5까지의 척도로 평가하세요. 여기서 0은 \"의미 중복 없음\"이고 5는 \"같은 의미\"입니다.\n\n{options_}", "{answer_str}"),
        ("{sentence1}\n{sentence2}\n\n0에서 5까지의 점수에서 0은 \"의미 중복 없음\"이고 5는 \"같은 의미\"인 경우, 첫 번째 문장은 두 번째 문장과 얼마나 비슷합니까?\n\n{options_}", "{answer_str}"),
        ("문장 1: {sentence1}\n\n 문장 2: {sentence2}\n\n0에서 5까지(0=\"의미 중복 없음\", 5=\"같은 의미\"), 두 문장은 얼마나 유사합니까?\n\n{options_}", "{answer_str}"),
        ("다음 두 문장은 얼마나 비슷한가요? \n\n{sentence1}\n{sentence2}\n\n0~5까지의 점수로 답하세요. 여기서 0은 \"전혀 유사하지 않다\"이고 5는 \"같은 의미\"입니다.\n\n{options_}", "{answer_str}"),
        ("다음 문장은 같은 것을 말합니까?\n\n{sentence1}\n{sentence2}\n\n0은 \"유사하지 않음\"이고 5는 \"매우 유사함\"입니다.\n\n{options_}", "{answer_str}"),
        ("다음 두 문장의 유사성을 0에서 5까지의 점수로 평가하세요. 여기서 0은 \"의미 중복 없음\", 5는 \"같은 의미\"입니다.\n\n{sentence1}\n{sentence2}\n\n{options_}", "{answer_str}"),
        ("0에서 5까지의 점수에서 0은 \"유사하지 않음\", 5는 \"매우 유사함\"인 경우, \"{sentence1}\"문장과 \"{sentence2}\" 문장은 얼마나 유사합니까?\n\n{options_}", "{answer_str}"),
        ("이 두 문장은 0-5(0은 \"유사하지 않음\", 5는 \"매우 유사함\")의 척도로 얼마나 유사합니까?\n\n{sentence1}\n{sentence2}\n\n{options_}", "{answer_str}"),
        ("{sentence1}\n\n위 문장과 텍스트 유사도가 0에서 5 사이의 점수로 {answer_str}인 새 문장을 생성하세요.", "{sentence2}"),
        ("{sentence2}\n\n위 문장과 텍스트 유사성 측면에서 (0에서 5까지의 점수에서) 5점 만점에 {answer_str}에 해당하는 문장은 무엇입니까?", "{sentence1}"),
    ],
    "klue_sts": [
        ("{sentence1}\n{sentence2}\n\n이 두 문장은 같은 의미인가요? \n{options_}", "{answer}"),
        ("{sentence1}\n{sentence2}\n\n이 두 문장은 서로 의역인가요? \n{options_}", "{answer}"),
        ("1. {sentence1}\n2. {sentence2}\n\nA이 두 문장은 서로 의역인가요? \n{options_}", "{answer}"),
        ("(1) {sentence1}\n(2) {sentence2}\n\n이 두 문장은 같은 의미인가요?\n\n{options_}", "{answer}"),
        ("문장 1: {sentence1}\n문장 2: {sentence2}\n\n이 두 문장은 같은 뜻을 담고 있습니까?\n\n{options_}", "{answer}"),
        ("위키피디아의 이 두 문장은 같은 의미인가요?\n{sentence1}\n{sentence2}\n\n{options_}", "{answer}"),
        ("같은 의미인가요?\n{sentence1}\n{sentence2}\n\n{options_}", "{answer}"),
        ("이것들은 의역인가요?\n{sentence1}\n{sentence2}\n\n{options_}", "{answer}"),
        ("이것들이 같은 의미인가요?\n{sentence1}\n{sentence2}\n\n{options_}", "{answer}"),
        ("이것들이 같은 의미인지 확인해 주세요. 같으면 \"네\"로 응답하고, 그렇지 않으면 \"아니오\"로 응답하세요.\n{sentence1}\n{sentence2}", "{answer}"),
    ],
    "klue_nli": [
        ("전제: {premise}\n\n가설: {hypothesis}\n\n전제가 가설을 수반합니까?\n\n{options_}", "{answer}"),
        ("전제: {premise}\n가설: {hypothesis}\n가설이 전제를 수반합니까?\n{options_}", "{answer}"),
        ("여기에 전제가 있습니다:\n{premise}\n\n여기에 가설이 있습니다:\n{hypothesis}\n\n전제가 참이면 가설도 참이라는 결론을 내릴 수 있습니까?\n{options_}", "{answer}"),
        ("문장 1: {premise}\n\n문장 2: {hypothesis}\n이 두 번째 문장은 첫 번째 문장에 의해 수반되는가?\n\n{options_}", "{answer}"),
        ("문장 1: {premise}\n\n문장 2: {hypothesis}\n\n첫 번째 문장이 참이면 두 번째 문장도 참입니까?\n{options_}", "{answer}"),
        ("전제 \"{premise}\"에 근거하여, 가설 \"{hypothesis}\"가 참이라는 결론을 내릴 수 있습니까?\n\n{options_}", "{answer}"),
        ("전제: \"{premise}\" 이 전제가 참이면 \"{hypothesis}\"라는 가설이 수반되는지 여부에 대해 무엇을 알 수 있나요?\n\n{options_}", "{answer}"),
        ("Premise:\n\"{premise}\" 이 전제에 따라 가설 \"{hypothesis}\"가 참입니까?\n{options_}", "{answer}"),
        ("만약 {premise}라면 \"{hypothesis}\"이라고 결론을 내릴 수 있습니까?\n{options_}", "{answer}"),
        ("{premise}\n\n\"다음 \"{hypothesis}\"을 따르나요?\n{options_}", "{answer}"),
    ],
    "klue_ynat": [
        ("{title}\n\n이 뉴스 제목은 무엇에 관한 글인가요?\n{options_}", "{answer}"),
        ("{title}\n\n이 뉴스 제목은 어떤 주제에 관한 문서인가요?\n{options_}", "{answer}"),
        ("{title}\n\n이 뉴스 제목에 대한 가장 좋은 카테고리는 무엇입니까?\n{options_}", "{answer}"),
        ("{title}\n\n이 뉴스 제목은 무엇에 관한 것인가요?\n{options_}", "{answer}"),
        ("{title}\n\n위 뉴스 제목에 가장 알맞은 카테고리는 무엇인가요?\n{options_}", "{answer}"),
    ],
    'kor_translate': [  # Yujung
        ("{sent1}\n\n{lang2}로 번역하세요.", "{sent2}"),
        ("{sent2}\n\n{lang1}로 번역하세요.", "{sent1}"),
        ("{sent2}\n\n{lang1}로 번역 해줄 수 있나요?", "{sent1}"),
        ("{sent2}\n\n{lang1}로 번역할까요?", "{sent1}"),
        ("{lang2}로 번역하세요:\n\n{sent1}", "{sent2}"),
        ("다음 문장을 {lang2}로 번역하세요.\n{sent1}", "{sent2}"),
        ("\"{sent1}\"를 {lang2}로 어떻게 하나요?", "{sent2}"),
        ("\"{sent1}\"을 {lang2}로 번역할까요?", "{sent2}"),
        ("{lang1}가 아닌 문장을 쓰세요.", "{sent2}"),
        ("{sent2}\n\n무슨 언어일까요?", "{lang2}"),
    ],
    'ko_summary1': [  # Yujung # gigaword
        ("다음 텍스트에 대한 간단한 요약를 작성하세요: {text}", "{summary}"),
        ("이 문장을 간략하게 요약하세요: {text}", "{summary}"),
        ("이 문장에 대한 간단한 요약을 생성하세요:\n{text}", "{summary}"),
        ("이 문장의 더 짧은 버전은 무엇인가요:\n\n{text}", "{summary}"),
        ("{text}\n\n한 문장 이하의 간단한 요약을 작성하세요", "{summary}"),
        ("{text}\n\n위 텍스트의 아주 짧은 요약은 무엇인가요?", "{summary}"),
        ("{text}\n앞서 언급한 텍스트를 한 구절로 요약하세요.", "{summary}"),
        ("{text}\n위 단락에 대한 간단한 요약을 생성할 수 있나요?", "{summary}"),
        ("이 요약에 따라 문장을 작성하세요: {summary}", "{text}"),
        ("\"{summary}\"를 기반으로 문장을 작성하세요.", "{text}"),
    ],
    'ko_summary2': [
        ("다음 문서에 대한 간단한 요약를 작성하세요: {title}\n\n{text}", "{summary}"),
        ("이 문서를 간략하게 요약하세요: {title}\n\n{text}", "{summary}"),
        ("이 문서에 대한 간단한 요약을 생성하세요:\n\n{title}\n\n{text}", "{summary}"),
        ("이 문서의 더 짧은 버전은 무엇인가요:\n\n{title}\n\n{text}", "{summary}"),
        ("{title}\n\n{text}\n\n한 문장 이하의 간단한 요약을 작성하세요", "{summary}"),
        ("{title}\n\n{text}\n\n위 문서의 아주 짧은 요약은 무엇인가요?", "{summary}"),
        ("{title}\n\n{text}\n앞서 언급한 문서를 한 구절로 요약하세요.", "{summary}"),
        ("{title}\n\n{text}\n위 단락에 대한 간단한 요약을 생성할 수 있나요?", "{summary}"),
        ("이 요약에 따라 문서를 작성하세요: {summary}", "{text}"),
        ("\"{summary}\"를 기반으로 제목을 작성하세요.", "{title}"),
    ],
    'ko_summary_news': [  # Yujung
        ("이 기사를 요약하세요:\n\n{text}", "{summary}"),
        ("이 문서에 기반한 요약 작성하세요:\n\n{text}", "{summary}"),
        ("Article:\n\n{text}\n요약한다면 무엇일까요?", "{summary}"),
        ("{text}\n위 기사에 대한 한 문단 요약은 무엇인가요?", "{summary}"),
        ("다음은 뉴스 기사입니다: {text}\n이 기사의 요약은 무엇인가요?", "{summary}"),
        ("뉴스 기사:\n\n{text}\n위 기사의 더 짧은 버전은 무엇인가요?", "{summary}"),
        ("{text}\n\n요약을 작성하세요.", "{summary}"),
        ("기사:\n{text}요약:\n", "{summary}"),
        ("이 요약을 기반으로 기사 작성:\n\n{summary}", "{text}"),
        ("{summary}\n\n이 요약을 풀어서 작성해주세요.", "{text}"),
    ],
    'ko_summary_newsroom': [  # Yujung
        ("{title}\n\n{text}\n\n한 두 문장으로 요약을 작성하세요.", "{summary}"),
        ("다음 기사에 대한 간단한 요약을 작성하세요:\n\n{title}\n\n{text}", "{summary}"),
        ("이 뉴스 기사를 간략하게 요약해 주세요:\n\n{title}\n\n{text}", "{summary}"),
        ("{title}\n{text}\n이 기사는 무엇에 관한 기사입니까?", "{summary}"),
        ("{title}\n{text}\n위 기사의 간단한 요약은 무엇인가요?", "{summary}"),
        ("{title}\n\n{text}\n이 텍스트에서 가장 중요한 부분은 무엇인가요?", "{summary}"),
        ("뉴스 기사: {title}\n\n{text}\n이 뉴스 기사에서 가장 중요한 부분은 무엇인가요?", "{summary}"),
        ("제목이 {title}인 기사를 작성하세요.", "{text}"),
        ("이 기사의 제목을 작성하세요:\n\n{text}", "{title}"),
        ("여기 문서가 있습니다:\n\n{text}\n\n이 문서에 대한 제목을 작성하세요.", "{title}"),
    ],
    'ko_summary_dialogue': [  # Yujung
        ("{dialogue}\n\n위의 대화를 간략히 요약하세요.", "{summary}"),
        ("여기 대화가 있습니다:\n{dialogue}\n\n간단한 요약을 작성하세요!", "{summary}"),
        ("대화:\n{dialogue}\n\n이 대화의 요약은 무엇인가요?", "{summary}"),
        ("{dialogue}\n\n두 문장 이내로, 이 대화는 무엇에 관한 대화였나요?", "{summary}"),
        ("다음은 대화입니다:\n{dialogue}\n\n어떤 대화였나요?", "{summary}"),
        ("대화:\n{dialogue}\n그 대화의 요점은 무엇입니까?", "{summary}"),
        ("대화:\n{dialogue}\n그 대화에서 무슨 일이 있었나요?", "{summary}"),
        ("원하는 내용에 대해 대화를 작성하세요", "{dialogue}"),
        ("이 요약을 바탕으로 대화를 작성하세요:\n{summary}.", "{dialogue}"),
        ("이 전제하에 \"{summary}\"으로 대화를 작성하십시오.", "{dialogue}"),
    ]

}